---
title: "Practical Prose of Harry Potter"
format:
  html: 
    toc: true
    page-layout: full
---

At the beginning of 2023, I embarked on a journey of reading the *Harry Potter* series by British author J.K. Rowling. I had a basic familiarity with the fictional universe. My sister was a fanatic when I was in my pre-teen years, so I got exposed to the films, but never delved into the books. 

It took me almost a year to get through the over 4,000-page series. All seven original books plus the screenplay, *Harry Potter and the Cursed Child*. My journey isn’t over as the Wizarding World continues to create more content to consume. The Hogwarts Library collection of books is next on my radar, especially *Fantastic Beasts and Where to Find Them* and *The Tales of Beedle The Bard*. 

There were several quotes, at least a couple from each book in the series, that moved me. Page numbers for the original series quotes come from the Kindle version of *Harry Potter: The Complete Collection*.


## Philosopher's Stone

> “No two Ollivander wands are the same, just as no two unicorns, dragons, or phoenixes are quite the same. And of course, you never get such good results with another wizard’s wand.” (85)

Trying to be someone else is a common inclination. While it’s a good idea to integrate the good and refrain from the bad of others, Ollivander reminds us of the harm in disregarding your authentic self and being someone that is not truly you.

> “Harry played with chessmen Seamus Finnigan had lent him and they didn’t trust him at all. He wasn’t a very good player yet and they kept shouting different bits of advice at him, which was confusing: ‘Don’t send me there, can’t you see his knight? Send him, we can afford to lose him.’” (193)

This is small but significant lesson in leadership. How can one tell others what to do if a trusting relationship has not been developed first? 

> “It does not do to dwell on dreams and forget to live, remember that.” (207)

Here, we see Dumbledore instilling a bias for action in Harry early on. When you lose your parents as a baby, you are particularly vulnerable to the ruminating qualities of wishing and hoping. Dumbledore is persuasive in advising Harry against it.

> “Books! And cleverness! There are more important things – friendship and bravery.” (277)

If there was one character in the series that when they spoke, I listened, it was Hermione. Not only does this show why she is in Gryffindor and not Ravenclaw, it describes that what matters most in life is who you spend it with and what you do, not what you know. 

> “To the well-organized mind, death is but the next great adventure. You know, the stone was really not such a wonderful thing. As much money and life as you could want! The two things most human beings would choose above all – the trouble is, humans do have a knack of choosing precisely those things which are worst for them.” (288)

Unlimited money and time won’t fulfill us, yet we try to seek more of it every day. Dumbledore reminds us to think about the “why” of our choices more thoroughly. If we run on autopilot, we could end up choosing things that do us more harm than good. 

> “There are all kinds of courage. It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends. I therefore award ten points to Mr. Neville Longbottom.” (296)

Standing in the way of the three coolest first years in your house as they go to protect the Philosopher’s Stone is unlikely to help you fit in. But Neville is a leader. He acts in the best interests of Gryffindor, doing what he thinks is right even if it means sacrificing his friendships.

## Chamber of Secrets

> “Never trust anything that can think for itself if you can’t see where it keeps its brain.” (651)

Mr Weasley’s remark is especially important as the modern world becomes more complex. We are required to think more critically about the information we consume and the tools we use. Like ChatGPT, there are plenty of things we don’t understand well, yet blindly trust. 

> “It is our choices, Harry, that show what we truly are, far more than our abilities.” (656)

Similar to Hermione’s quote on books and cleverness, Dumbledore says that we are judged by what we do, the actions we take. One can have tremendous talent and skill, but if it isn’t used in a meaningful way through our choices, then what good is it?

## Prisoner of Azkaban

> Ron: “What are you doing Muggle Studies for? You’re Muggle-born! Your mom and dad are Muggles! You already know all about Muggles!” \
> Hermione: “But it’ll be fascinating to study them from the wizarding point of view.” (722)

This is a minor dialogue between two characters that bicker through most of the book, but it demonstrates Hermione’s thirst for knowledge. When it is so easy to get the gist of something from one point of view, going deeper and opening yourself up to multiple perspectives is a valuable practice.

> “Harry sat stunned for a moment at the idea of someone having their soul sucked out through their mouth. But then he thought of Black.” \
> Harry: “He deserves it.” \
> Lupin: “You think so? Do you really think anyone deserves that?” (901)

Lupin’s question opens our eyes to the idea of being compassionate towards our enemies.

> “I knew I could do it this time, because I’d already done it…” (1059)

Confidence and belief in oneself requires evidence. Harry conjures a supremely impressive Patronus because he saw himself do it before all the Time-Turnering, and saves both Sirius and himself as a result. 

A remark in the 2004 film by Dumbledore in his opening address to the school stands out.

> “Happiness can be found, even in the darkest of times, if one only remembers to turn on the light.”

This reminds me that happiness is found through our own autonomy. It doesn’t just appear for people. You must take the initiative to turn on the light. To do good, mingle with good people, and to think positively. 

## Goblet of Fire

> “that would be Hermione’s advice: go straight to the Headmaster of Hogwarts, and in the meantime, consult a book.” (1107)

I mean, pretty simple but good advice for any challenge in your life – get help. Whether it is from a trusted individual like Dumbledore or a trusted book. 

> “Where’s the fun without a bit of risk?” (1268)

While everyone else warned about his ineligibility and that people have died competing in the Triwizard Tournament, Fred defends his decision to enter. We shouldn’t assume that risk is all bad. In fact, one of the riskiest things you can do in life is not take risks. When we take risks, the worst thing that can usually happen is failing and this is our greatest teacher. This quote reminds me of what Sirius says to Harry before sending him off to school in the *Order of Phoenix* (2007) film: “What’s life without a little risk?”

> “He thought back to how he’d felt while dodging the Horntail and compared it to the long wait before he’d walked out to face it…there was no comparison, the wait had been immeasurably worse.” (1433)

In a moment of reflection after completing the first task of the Triwizard Tournament, Harry discovers an important attribute of fear. The build-up to an action that scares you is actually much worse than the action itself. If something scares me, I try to push myself to do it right away because I know if I wait, i) the anxiety will make me feel terrible, and ii) the less likely I am to act. For example, if a question comes to mind during a lecture at school, I try to raise my hand right away to prevent hesitation and questioning myself.

> “If you are holding out for universal popularity, I’m afraid you will be in this cabin for a very long time.” (1521)

When Rita Skeeter writes about Hagrid being a half-giant in the Daily Prophet and letters come to Hogwarts calling for him to be sacked, Dumbledore reminds us that not everybody is going to like you and you can’t make everybody happy. But that shouldn’t stop you from living. 

> “If you want to know what a man is like, take a good look at how he treats his inferiors, not his equals.” (1588)

While discussing their thoughts on Barry Crouch Sr’s treatment of Winky the house-elf, Sirius remarks the respect that we give people should not depend on their status. If we are exceptionally kind to our bosses, then we should be exceptionally kind to our subordinates. 

> “You place too much importance, and you always have done, on the so-called purity of blood! You fail to recognize that it matters not what someone is born, but what they grow to be!” (1762)

> "We are only as strong as we are united, as weak as we are divided…Differences of habit and language are nothing at all if our aims are identical and our hearts are open.” (1776)

Dumbledore’s modus operandi: It doesn’t matter who or what someone is. If they are on our side and aiding our mission, everything else is irrelevant.

## Order of Phoenix

> “we feel our futures lie outside the world of academic achievement.” (2041)

This is one of my sister’s favourite quotes. While my personality differs greatly from Fred and George, there is still value in this opinion. It helps me question the importance of getting good grades and reminds me that there are more important things in life. 

> “And what good’s theory going to be in the real world?” (2060)

There is little use to knowing something well if you can’t use for good in the world. We should be biased for active practice over passive memorization. 

> “He knew she was watching him for signs of weakness and he was not going to show any, not even if he had to sit there all night, cutting open his own hand with this quill…” (2085)

Maybe this is more of an inclination associated with masculinity but I believe we should avoid giving others power over us. This scene reminded me of the battles between Michael Jordan’s Chicago Bulls and the Detroit Pistons. The Bulls would get physically beat up every game, but Jordan would advise his teammates to not labour or whine, because that’s when the Pistons would know they’ve got you.

> “Fools who wear their hearts proudly on their sleeves, who cannot control their emotions, who wallow in sad memories and allow themselves to be provoked so easily – weak people, in other words – they stand no chance against his powers.” (2381)

It is a little ironic that Snape is the one advising to not ruminate in emotions when he never truly moves on from loving Lily. But there is wisdom here. Relying solely on emotion to guide our decisions is a flawed approach.

> “Indifference and neglect often do much more damage than outright dislike.” (2708)

This is an apt observation of the human condition by Dumbledore to justify Kreacher’s betrayal of Sirius. It feels counterintuitive that disregard hurts more than dislike. If you are disliked, I guess you matter to someone else in some way. But if you are disregarded, your existence is perceived as insignificant. 

There are two quotes from the 2007 film that struck a chord with me. 

> “Every great wizard in history started out as nothing more than we are now: students. If they can do it, why not us?” 

In every pursuit, the individual has a beginning. Michael Jordan didn’t start out as a top NBA prospect. He started out playing basketball against his brothers and getting cut from the high school team. I find it helpful to learn about people who have pursued similar paths of that which you want to follow. We should remind ourselves that if it’s been done before, it can be done again.

> “The world isn’t split into good people and death eaters. We’ve all got both light and dark inside us. What matters is the part we choose to act on.”

This quote by Sirius summarizes the main theme of the series and mirrors Dumbledore’s earlier quote that we are defined by our choices. Even if we have these negative inclinations in us (for Harry, quite literally through a physical piece of Voldemort), we have the power to choose.

## Half-Blood Prince

> “I realized I can’t shut myself away or – or crack up. Sirius wouldn’t have wanted that, would he? And anyway, life’s too short” (2827)

It’s okay to grieve, but we also need to recover and come back stronger from adversities in our life. We can’t keep ourselves stuck in the past. 

> “It is the unknown we fear when we look upon death and darkness, nothing more.” (3302) 

Why do we fear something? The root cause in most cases is uncertainty. Instead of trying to better manage our fears, we should be thinking about how to better manage our relationship with uncertainty. 

> “There was so much he never asked him, so much he should have said…” (3375)

Harry is working through regret, which is something we constantly think about. It’s painful to think, “I should have done something,” because we can’t go back and change it. Consequently, we should make the most of our relationships today as they might be gone tomorrow. 

I loved the ending of the 2009 film where Harry, Ron, and Hermione are looking out from the Astronomy Tower at Fawkes flying across the landscape. Harry remarks: 

> “I never realized how beautiful this place was.” 

The trio have had enough to deal with every year that it is forgivable if they’ve never  had a mindful moment, basking in and appreciating the beauty of Hogwarts. Harry seems to be perpetually focused on a mission so seeing him focused on the present and the beauty before him, is a reminder to step back and be grateful. Have an appreciation for the place we are in, throughout the experience, not just at the end. 

## Deathly Hallows

> “he could find something to value in anyone, however apparently insignificant or wretched” (3409)

Doge captures the essence of Dumbledore with this statement. Dumbledore found nobody in his life to be disposable. He searched for the good and then worked to bring it out of you. 

> “And yet the fiercer the longing for the Hallows burned inside him, the less joyful it made him…felt quite isolated from the other two.” (3814)

We see here the tragic consequence of being vain and ambitiously selfish. We sacrifice connection with those around us. 

> “The thing is, it helps when people stand up to them, it gives everyone hope. I used to notice that when you did it, Harry.” (3947)

This is another example of how belief in something requires evidence. It is so much easier to do something once you know that it’s been done before. Just like the influx of successful summits after Edmund Hillary finally reached the top of Everest. Sometimes though, we have to be like Harry or Edmund, and do the thing for the first time without inspiration from others.

> Snape: “– mediocre, arrogant as his father, a determined rule-breaker, delighted to find himself famous, attention-seeking and impertinent –” \
Dumbledore: “You see what you expect to see, Severus” (4050)

This is a perfect example of confirmation bias. We search for and favour information that confirms our prior beliefs. Before even meeting Harry, Snape assumed he would be just like his father. So, everything that he picks up on about Harry supports this assumption. This bias really warps the truth for Snape because us readers know that his characterization of Harry is inaccurate.

> “That which Voldemort does not value, he takes no trouble to comprehend.” (4078)

Since Voldemort does not value love, he never understands how Lily’s protective enchantment works on Harry, and this leads to his ultimate self-sabotage. This quote makes me think about how we struggle to learn certain subjects. The subjects we most struggle to grasp are usually those we don’t value. If I think understanding chemistry is pointless and provides no value, then it’s going to be tough to learn it. If you’re struggling to learn a subject, search for something in it that resonates with you.

> “Those who are best suited for power are those who have never sought it. Those who, like you, have leadership thrust upon them, and take up the mantle because they must.” (4086)

Leadership cannot be forced. Harry demonstrates his incredible leadership ability when heading Dumbledore’s Army in the fifth book. But that was because there was great need for it. They would have never been prepared for Voldemort if they continued letting the Ministry reform education at Hogwarts.  

>Harry: “Is this real? Or has this been happening inside my head?” \
Dumbledore: “Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?” (4091)

After facing Voldemort’s killing curse, Harry finds himself in this heaven-like place and strikes up a casual conversation with Dumbledore. Just kidding, this conversation reveals pretty much everything, clearing up most unanswered questions. But like Harry, I wouldn’t be able to tell if it was real or imaginary. While this line may lack practical advice, it reveals an important perspective that we should all ponder. 

In the 2011 film, *Harry Potter and the Deathly Hallows: Part 2*, Lupin drops some wisdom while he and Kinsley prepare for battle.

> “It is the quality of one’s convictions that determine success, not the number of followers.”

This quote highlights why they have a good chance against Voldemort, even though his army is better. It’s because they have stronger belief in what they are doing. Most of Voldemort’s followers are there out of fear of what would happen to them if they resisted. Most of them don’t care about the Voldemort’s mission to kill Harry. But everyone on Harry’s side is committed and believes in the mission to destroy Voldemort. That’s their driving force.

## Cursed Child

> “If you answer the gossip, you feed the gossip.” (24)

I try to live a drama free life so there is little to no gossip surrounding me. But this is a nice general rule for how to handle gossip. By acknowledging and speaking on the gossip, you are increasing its importance so sometimes no comment is best.

> “Perfection is beyond the reach of humankind, beyond the reach of magic. In every shining moment of happiness is that drop of poison: the knowledge that pain will come again. Be honest to those you love, show your pain. To suffer is as human as to breathe.” (258)

Oh, those headmaster portraits. If only we could talk with portraits of the dead in real life. Dumbledore understands things very well. Here, he hits hard on balance. Life is not perfect, and further, it is never always good. Pain is inevitable and it is okay. If suffering is going to happen, you might as well not resist it. Embrace it because it is a normal human experience.

## Concluding Thoughts

I went into this endeavour as someone who only read non-fiction. I doubted how much the fiction genre could add to my life. But after finishing the *Harry Potter* series, my mind has certainly changed. Not only was it full of practical prose that will help me be a better person, but it was also entertaining for me. Seeing how the characters developed and the plot advanced, even after having seen the films, was something I looked forward to every time I sat down to read.


